insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (1, 'FIAT', 'Palio', 2020, 2021, 59825, 'Um modelo bastante conhecido no país, oferecendo espaço e economia.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (2, 'VOLKSWAGEN', 'Gol', 2019, 2019, 46826, 'Um dos carros mais tradicionais no Brasil, conhecido pela durabilidade e desempenho.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (3, 'FIAT', 'Strada', 2017, 2017, 51833, 'Uma picape compacta muito popular no mercado brasileiro, conhecida pela versatilidade.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (4, 'CHEVROLET', 'Onix', 2022, 2022, 76891, 'Líder de vendas por vários anos, é um hatch compacto com boa eficiência de combustível.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (5, 'FORD', 'Ka', 2014, 2014, 38736, 'Um hatch compacto que ganhou popularidade no Brasil devido ao design moderno e eficiência.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (6, 'RENAULT', 'Kwid', 2017, 2017, 41709, 'Um carro compacto com foco em economia de combustível e praticidade urbana.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (7, 'CHEVROLET', 'Prisma', 2007, 2007, 21901, 'Sedã compacto que compartilha a plataforma com o Chevrolet Onix.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (8, 'TOYOTA', 'Corolla', 2010, 2010, 53445, 'Um dos sedãs mais vendidos no mundo, conhecido por sua confiabilidade e conforto.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (9, 'HYUNDAI', 'HB20', 2014, 2014, 43671, 'Um hatch compacto da marca sul-coreana, que ganhou espaço no mercado brasileiro.');
insert into carro (id_carro, marca, modelo, ano_fabricacao, ano_modelo, valor, descricao) values (10, 'FIAT', 'Toro', 2015, 2016, 89854, 'Uma picape compacta com design moderno e características que a tornam uma opção interessante para diferentes perfis de consumidores.');

insert into usuario (id_usuario, email, senha, nome, ativo, data_nascimento, data_cadastro) values (1, 'joao@gmail.com', '12345678', 'João Silva Alves', 1, '1998-08-10', '2020-01-01 10:01:18');
insert into usuario (id_usuario, email, senha, nome, ativo, data_nascimento, data_cadastro) values (2, 'maria@gmail.com', '12345678', 'Maria Silva Alves', 1, '1997-08-10', '2020-02-01 10:01:18');
insert into usuario (id_usuario, email, senha, nome, ativo, data_nascimento, data_cadastro) values (3, 'ana@gmail.com', '12345678', 'Ana Silva Alves', 1, '2000-08-10', '2020-03-01 10:01:18');
insert into usuario (id_usuario, email, senha, nome, ativo, data_nascimento, data_cadastro) values (4, 'carlos@gmail.com', '12345678', 'Carlos Alves', 1, '2001-08-10', '2020-04-01 10:01:18');
